theme: jekyll-theme-cayman
title: Ricardo Ogando - Observatório Nacional, RJ, Brazil
description: Astrophysicist at [Observatório Nacional](https://www.gov.br/observatorio/pt-br), Rio de Janeiro, Brazil

You can contact me at ogando@on.br

For outreach and random things follow me at [Twitter](https://twitter.com/rilogando)

PS. My other page is http://staff.on.br/ogando (currently offline due to Brazil government ill policies)
